version: 2

updates:
  # Enable version updates for bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "vibeerrors/maintainers"
    assignees:
      - "vibeerrors/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    
  # Enable version updates for sample app
  - package-ecosystem: "bundler"
    directory: "/sample_app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vibeerrors/maintainers"
    assignees:
      - "vibeerrors/maintainers"
    commit-message:
      prefix: "deps(sample)"
      include: "scope"
    labels:
      - "dependencies"
      - "sample-app"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vibeerrors/maintainers"
    assignees:
      - "vibeerrors/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"